name: 🔨 Build Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install libpcap-dev
        run: sudo apt install libpcap-dev

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
        working-directory: .
      
      - name: Build Intercept
        run: go build .
        working-directory: cmd/intercept/

      - name: Build Collab
        run: go build .
        working-directory: cmd/collab/
